/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f4f6",
        "surface-container": "#eeeeef",
        "surface-container-high": "#e5e7eb",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9fa",
        "outline": "#64748b",
        "outline-variant": "#e2e8f0",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "primary": "#1d4ed8",
        "primary-container": "#1d4ed8",
        "on-primary": "#ffffff",
        "secondary": "#475569",
        "secondary-container": "#f1f5f9",
        "on-secondary-fixed": "#0f172a",
        "error": "#b91c1c",
        "error-container": "#fef2f2",
        "on-error-container": "#991b1b",
        "warning": "#d97706",
        "warning-container": "#fffbeb",
        "on-warning-container": "#92400e",
        "success": "#15803d",
        "success-container": "#f0fdf4",
        "on-success-container": "#166534",
        brand: {
          50: '#f0f7ff',
          100: '#e0effe',
          500: '#1d4ed8',
          600: '#1e40af',
          700: '#1d4ed8',
          900: '#0f172a',
        },
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "code-md": ["JetBrains Mono", "monospace"],
        "code-lg": ["JetBrains Mono", "monospace"],
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
}
