/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#0b0f19",
        "surface-container": "#0f1422",
        "surface-container-high": "#161d30",
        "surface-container-lowest": "#070a12",
        "surface": "#090d16",
        "outline": "#334155",
        "outline-variant": "rgba(255, 255, 255, 0.08)",
        "on-surface": "#f1f5f9",
        "on-surface-variant": "#94a3b8",
        "primary": "#38bdf8",
        "primary-container": "rgba(56, 189, 248, 0.15)",
        "on-primary": "#030712",
        "secondary": "#94a3b8",
        "secondary-container": "#1e293b",
        "on-secondary-fixed": "#f1f5f9",
        "error": "#f43f5e",
        "error-container": "rgba(244, 63, 94, 0.15)",
        "on-error-container": "#fecdd3",
        "warning": "#f59e0b",
        "warning-container": "rgba(245, 158, 11, 0.15)",
        "on-warning-container": "#fde68a",
        "success": "#10b981",
        "success-container": "rgba(16, 185, 129, 0.15)",
        "on-success-container": "#a7f3d0",
        brand: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          900: '#0c4a6e',
          950: '#082f49',
        },
      },
      fontFamily: {
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "headline-xl": ["'Space Grotesk'", "sans-serif"],
        "headline-lg": ["'Space Grotesk'", "sans-serif"],
        "headline-md": ["'Space Grotesk'", "sans-serif"],
        "headline-sm": ["'Space Grotesk'", "sans-serif"],
        "label-md": ["'Plus Jakarta Sans'", "sans-serif"],
        "label-sm": ["'Plus Jakarta Sans'", "sans-serif"],
        "code-sm": ["'JetBrains Mono'", "monospace"],
        "code-md": ["'JetBrains Mono'", "monospace"],
        "code-lg": ["'JetBrains Mono'", "monospace"],
        sans: ["'Plus Jakarta Sans'", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        mono: ["'JetBrains Mono'", "'Space Mono'", "monospace"],
        space: ["'Space Grotesk'", "sans-serif"],
        "space-grotesk": ["'Space Grotesk'", "sans-serif"],
        unbounded: ["'Unbounded'", "sans-serif"],
        chakra: ["'Chakra Petch'", "sans-serif"],
      },
    },
  },
  plugins: [],
}
