"""Backend-controlled professional PDF generator for Phase 5 Regulatory Dossier.

Generates a statutory-grade regulatory engineering document using ReportLab:
- Clean typography and structured section hierarchy (1 to 20)
- Document control headers/footers with dynamic page numbering ('Page X of Y')
- Explicit statutory disclaimers prohibiting false BIS claims
- Tabular displays with stable IDs, hashes, and mathematical assessment results
"""

import os
import io
import hashlib
from typing import Dict, Any, List
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """Two-pass canvas to dynamically compute and render total page count ('Page X of Y')."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Header (pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 755, "ZYNTRIX — REGULATORY DOSSIER & COMPLIANCE PASSPORT")
            self.drawRightString(558, 755, "CONFIDENTIAL / ENGINEERING AUDIT")
            self.setStrokeColor(colors.HexColor("#CBD5E1"))
            self.setLineWidth(0.5)
            self.line(54, 748, 558, 748)

        # Footer (all pages)
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        self.drawString(54, 32, "Generated by Zyntrix — Regulatory Engineering Workstation")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_text)
        self.restoreState()


def generate_dossier_pdf(
    dossier_data: Dict[str, Any],
    sections: List[Dict[str, Any]],
    output_path: str,
) -> Dict[str, Any]:
    """
    Generate authoritative, reproducible PDF regulatory dossier.
    Saves file to output_path and returns file metadata including SHA-256 digest.
    """
    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=54,
    )

    styles = getSampleStyleSheet()
    
    # Custom typography styles
    title_style = ParagraphStyle(
        "DossierTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=8,
    )
    subtitle_style = ParagraphStyle(
        "DossierSubtitle",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#475569"),
        spaceAfter=14,
    )
    h1_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#1E293B"),
        spaceBefore=12,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        "DossierBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11.5,
        textColor=colors.HexColor("#1E293B"),
    )
    bold_body = ParagraphStyle(
        "DossierBoldBody",
        parent=body_style,
        fontName="Helvetica-Bold",
    )
    table_cell = ParagraphStyle(
        "TableCell",
        parent=body_style,
        fontSize=7.5,
        leading=9.5,
    )
    table_cell_bold = ParagraphStyle(
        "TableCellBold",
        parent=table_cell,
        fontName="Helvetica-Bold",
    )
    code_cell = ParagraphStyle(
        "CodeCell",
        parent=table_cell,
        fontName="Courier",
        fontSize=7,
        leading=8.5,
        textColor=colors.HexColor("#334155"),
    )
    disclaimer_style = ParagraphStyle(
        "DisclaimerBox",
        parent=body_style,
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#991B1B"),
        fontName="Helvetica-Bold",
    )

    elements = []

    # 1. Cover / Regulatory Header
    elements.append(Paragraph(dossier_data.get("title", "REGULATORY FILING DOSSIER"), title_style))
    elements.append(Paragraph(
        f"Compliance Job: <b>{dossier_data.get('job_id')}</b> | Version: <b>v{dossier_data.get('version')}</b> | Generated: {dossier_data.get('generated_at')}",
        subtitle_style,
    ))

    # Prominent Statutory Disclaimer Banner
    disclaimer_text = (
        "<b>STATUTORY REGULATORY DISCLAIMER:</b><br/>"
        "Zyntrix is an engineering workstation providing deterministic compliance evaluation, evidence traceability, "
        "and technical documentation. This document does <b>NOT</b> constitute a Bureau of Indian Standards (BIS) license, "
        "statutory certification, or regulatory approval. Authoritative certification must be obtained directly from "
        "the appropriate statutory authority following mandatory physical conformity assessments."
    )
    disclaimer_table = Table(
        [[Paragraph(disclaimer_text, disclaimer_style)]],
        colWidths=[486],
    )
    disclaimer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FEF2F2")),
        ("BORDER", (0, 0), (-1, -1), 1, colors.HexColor("#F87171")),
        ("PADDING", (0, 0), (-1, -1), 8),
    ]))
    elements.append(disclaimer_table)
    elements.append(Spacer(1, 14))

    # Document Control Metadata Box
    doc_meta_data = [
        [Paragraph("<b>Dossier ID:</b>", table_cell), Paragraph(str(dossier_data.get("id")), code_cell),
         Paragraph("<b>Assessment Run ID:</b>", table_cell), Paragraph(str(dossier_data.get("assessment_run_id")), code_cell)],
        [Paragraph("<b>Canonical Digest:</b>", table_cell), Paragraph(str(dossier_data.get("dossier_digest"))[:24] + "...", code_cell),
         Paragraph("<b>Engine Version:</b>", table_cell), Paragraph(str(dossier_data.get("assessment_engine_version")), table_cell)],
        [Paragraph("<b>Evidence Digest:</b>", table_cell), Paragraph(str(dossier_data.get("evidence_manifest_digest"))[:24] + "...", code_cell),
         Paragraph("<b>Product DNA Digest:</b>", table_cell), Paragraph(str(dossier_data.get("product_dna_digest"))[:24] + "...", code_cell)],
    ]
    meta_table = Table(doc_meta_data, colWidths=[100, 143, 110, 133])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ("PADDING", (0, 0), (-1, -1), 4),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 16))

    # Render each of the 20 Document Sections
    for sec in sorted(sections, key=lambda s: s.get("section_number", 0)):
        sec_num = sec.get("section_number")
        sec_title = sec.get("title", f"Section {sec_num}")
        content = sec.get("content_json", {})

        elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceBefore=8, spaceAfter=8))
        elements.append(Paragraph(f"<b>{sec_num}. {sec_title}</b>", h1_style))

        # Specialized rendering based on section key
        sec_key = sec.get("section_key")

        if sec_key == "TRACEABILITY_MATRIX":
            # Traceability table
            rows = content.get("matrix", [])
            table_data = [
                [
                    Paragraph("<b>Requirement</b>", table_cell_bold),
                    Paragraph("<b>DNA Fact</b>", table_cell_bold),
                    Paragraph("<b>Evidence / CAD</b>", table_cell_bold),
                    Paragraph("<b>Assessment</b>", table_cell_bold),
                    Paragraph("<b>Review / Attest</b>", table_cell_bold),
                ]
            ]
            for r in rows[:40]:  # Cap for PDF page sanity if extensive
                cad_info = f"<br/>CAD: {r.get('cad_measurement_id')}" if r.get("cad_measurement_id") != "N/A" else ""
                table_data.append([
                    Paragraph(f"<b>{r.get('requirement_id')}</b><br/>{r.get('clause')}", table_cell),
                    Paragraph(f"{r.get('parameter_key')}<br/>{r.get('dna_value')}", table_cell),
                    Paragraph(f"EVD: {r.get('evidence_id')}{cad_info}<br/>Status: {r.get('evidence_acceptance')}", table_cell),
                    Paragraph(f"<b>{r.get('assessment_state')}</b><br/>ID: {r.get('assessment_result_id')[:12]}...", table_cell),
                    Paragraph(f"Rev: {r.get('review_decision')}<br/>Att: {r.get('attestation_id')[:10] if r.get('attestation_id') != 'NONE' else 'NONE'}", table_cell),
                ])
            t = Table(table_data, colWidths=[90, 100, 110, 96, 90])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("PADDING", (0, 0), (-1, -1), 3),
            ]))
            elements.append(t)

        elif sec_key == "EVIDENCE_REGISTER":
            items = content.get("evidence_items", [])
            table_data = [
                [
                    Paragraph("<b>ID / File</b>", table_cell_bold),
                    Paragraph("<b>Type</b>", table_cell_bold),
                    Paragraph("<b>Status</b>", table_cell_bold),
                    Paragraph("<b>SHA-256 Hash</b>", table_cell_bold),
                ]
            ]
            for e in items:
                table_data.append([
                    Paragraph(f"<b>{e.get('id')}</b><br/>{e.get('file_name')}", table_cell),
                    Paragraph(str(e.get("file_type")), table_cell),
                    Paragraph(f"<b>{e.get('acceptance_status')}</b>", table_cell),
                    Paragraph(str(e.get("sha256_hash")), code_cell),
                ])
            t = Table(table_data, colWidths=[140, 70, 96, 180])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("PADDING", (0, 0), (-1, -1), 3),
            ]))
            elements.append(t)

        elif sec_key == "ASSESSMENT_RESULTS":
            results = content.get("results", [])
            table_data = [
                [
                    Paragraph("<b>Clause</b>", table_cell_bold),
                    Paragraph("<b>Parameter</b>", table_cell_bold),
                    Paragraph("<b>Observed vs Expected</b>", table_cell_bold),
                    Paragraph("<b>Outcome</b>", table_cell_bold),
                ]
            ]
            for res in results:
                obs = f"{res.get('observed_value', 'N/A')} {res.get('observed_unit', '')}".strip()
                exp = f"{res.get('comparison_operator', '')} {res.get('expected_value', '')}".strip()
                table_data.append([
                    Paragraph(str(res.get("clause_number")), table_cell_bold),
                    Paragraph(str(res.get("parameter_key") or "N/A"), table_cell),
                    Paragraph(f"Obs: {obs}<br/>Req: {exp}", table_cell),
                    Paragraph(f"<b>{res.get('assessment_state')}</b>", table_cell),
                ])
            t = Table(table_data, colWidths=[76, 120, 170, 120])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("PADDING", (0, 0), (-1, -1), 3),
            ]))
            elements.append(t)

        elif sec_key == "PRODUCT_DNA":
            params = content.get("parameters", [])
            table_data = [
                [
                    Paragraph("<b>Category</b>", table_cell_bold),
                    Paragraph("<b>Parameter</b>", table_cell_bold),
                    Paragraph("<b>Value</b>", table_cell_bold),
                    Paragraph("<b>Method</b>", table_cell_bold),
                    Paragraph("<b>Status</b>", table_cell_bold),
                ]
            ]
            for p in params:
                table_data.append([
                    Paragraph(str(p.get("category")), table_cell),
                    Paragraph(str(p.get("parameter")), table_cell_bold),
                    Paragraph(f"{p.get('value')} {p.get('unit', '')}".strip(), table_cell),
                    Paragraph(str(p.get("extraction_method") or "MANUAL"), table_cell),
                    Paragraph(str(p.get("status")), table_cell),
                ])
            t = Table(table_data, colWidths=[86, 120, 100, 100, 80])
            t.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                ("PADDING", (0, 0), (-1, -1), 3),
            ]))
            elements.append(t)

        else:
            # Generic text / dict rendering
            if isinstance(content, dict):
                for k, v in content.items():
                    if isinstance(v, (str, int, float, bool)):
                        elements.append(Paragraph(f"<b>{k.replace('_', ' ').capitalize()}:</b> {v}", body_style))
                        elements.append(Spacer(1, 2))
                    elif isinstance(v, list) and v and isinstance(v[0], str):
                        elements.append(Paragraph(f"<b>{k.replace('_', ' ').capitalize()}:</b> {', '.join(v)}", body_style))
                        elements.append(Spacer(1, 2))
            elif isinstance(content, str):
                elements.append(Paragraph(content, body_style))

        elements.append(Spacer(1, 8))

    # Build the document
    doc.build(elements, canvasmaker=NumberedCanvas)

    # Compute SHA-256 of generated PDF
    with open(output_path, "rb") as f:
        pdf_bytes = f.read()
    file_size = len(pdf_bytes)
    file_sha256 = hashlib.sha256(pdf_bytes).hexdigest()

    return {
        "file_path": output_path,
        "file_size_bytes": file_size,
        "sha256_hash": file_sha256,
    }
