"""Authoritative Seed Data for BIS Knowledge Intelligence (Phase 6).

Implements real, authoritative regulatory knowledge based on official Bureau of Indian Standards
specifications, MeitY Compulsory Registration Orders (CRO), and BIS Conformity Assessment Schemes.
"""

import hashlib
from datetime import datetime, timezone
from typing import List, Dict, Any


def compute_sha256(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


SEED_SOURCES: List[Dict[str, Any]] = [
    {
        "id": "src-bis-official-portal",
        "source_name": "Bureau of Indian Standards Official Standards Portal",
        "source_type": "AUTHORITATIVE_BIS",
        "source_url": "https://www.services.bis.gov.in",
        "publisher": "Bureau of Indian Standards (Govt of India)",
        "jurisdiction": "India",
        "publication_date": datetime(2024, 1, 1, tzinfo=timezone.utc),
        "metadata_json": {"authority_type": "STATUTORY_BODY", "act": "BIS Act 2016"},
    },
    {
        "id": "src-meity-cro",
        "source_name": "MeitY Compulsory Registration Order (CRO) Regulatory Schedule",
        "source_type": "AUTHORIZED_SOURCE",
        "source_url": "https://www.meity.gov.in/esdm/standards",
        "publisher": "Ministry of Electronics and Information Technology",
        "jurisdiction": "India",
        "publication_date": datetime(2023, 6, 1, tzinfo=timezone.utc),
        "metadata_json": {"order_reference": "CRO Phase I-V Schedules"},
    },
]

SEED_SCHEMES: List[Dict[str, Any]] = [
    {
        "scheme_code": "SCHEME_I",
        "scheme_name": "Scheme I — Product Certification Scheme (Standard Mark / ISI)",
        "governing_regulation": "BIS (Conformity Assessment) Regulations, 2018, Schedule II, Scheme I",
        "description": "Scheme I enables manufacturers to use the coveted ISI Standard Mark. It requires preliminary factory inspection, independent sampling, testing against Indian Standards, and continuous factory surveillance audit.",
        "applicable_products_summary": "Steel products, cement, household electrical cables, automotive safety glass, LPG cylinders, chemical fertilizers, packaged drinking water.",
        "process_overview": "1. Submission of application with test equipment details.\n2. Factory audit by BIS inspecting officer.\n3. Drawing of samples for independent testing in BIS lab.\n4. Grant of License (GoL) on satisfactory compliance.\n5. Post-grant surveillance through periodic factory and market samples.",
        "official_guideline_url": "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/product_certification",
    },
    {
        "scheme_code": "SCHEME_II_CRS",
        "scheme_name": "Scheme II — Compulsory Registration Scheme (CRS)",
        "governing_regulation": "BIS (Conformity Assessment) Regulations, 2018, Schedule II, Scheme II",
        "description": "Compulsory Registration Scheme for electronics and IT goods notified under MeitY and MNRE Quality Control Orders. Manufacturers register their products based on self-declaration of conformity and valid test reports from BIS-recognized laboratories.",
        "applicable_products_summary": "Grid-connected solar inverters, PV modules, laptops, tablets, mobile phones, LED lights, power adapters, secondary lithium batteries, smart meters.",
        "process_overview": "1. Sample product tested at a BIS-recognized laboratory.\n2. Test report generated in BIS portal.\n3. Manufacturer submits online application with Test Report and Undertaking.\n4. BIS scrutiny of documentation.\n5. Grant of Registration number (R-XXXXXXXX).\n6. Product marked with Standard Mark and Registration Number.",
        "official_guideline_url": "https://www.crsbis.in/BIS/",
    },
    {
        "scheme_code": "HALLMARKING_SCHEME",
        "scheme_name": "BIS Hallmarking Scheme for Precious Metals",
        "governing_regulation": "Hallmarking of Gold and Silver Artefacts Order, 2021",
        "description": "Statutory hallmarking certifying the fineness and purity of gold and silver jewelry. Managed through BIS recognized Assaying & Hallmarking Centres (AHC) using digital HUID (Hallmark Unique Identification).",
        "applicable_products_summary": "Gold jewelry and gold artefacts (14K, 18K, 20K, 22K, 23K, 24K) and silver articles.",
        "process_overview": "1. Jeweller registers online with BIS.\n2. Articles sent to BIS-recognized Assaying and Hallmarking Centre (AHC).\n3. Assay testing (XRF / Fire Assay) to determine exact purity.\n4. Laser-marking of 3 mandatory signs: BIS logo, purity fineness, and 6-digit alphanumeric HUID.\n5. Tracking and consumer verification via BIS CARE application.",
        "official_guideline_url": "https://www.services.bis.gov.in/php/BIS_2.0/bisconnect/hallmarking",
    },
]

SEED_SERVICES: List[Dict[str, Any]] = [
    {
        "service_name": "Product Certification (Grant of License under Scheme I)",
        "service_type": "PRODUCT_CERTIFICATION",
        "description": "Authoritative grant of license to manufacture and mark products with the standard ISI mark under Indian Standards.",
        "eligibility_criteria": "Manufacturing facilities with requisite in-house testing equipment, qualified quality control personnel, and conformity to product standard.",
        "step_by_step_procedure": "Step 1: Identify applicable IS standard.\nStep 2: Submit e-application via Manakonline portal with fee.\nStep 3: Factory verification by BIS officer.\nStep 4: Independent sample testing.\nStep 5: Issue of License certificate upon compliance.",
        "required_documents": ["Factory layout & machinery list", "In-house test equipment calibration certificates", "Raw material test certificates", "Manufacturing process flowchart", "Quality manual"],
        "portal_url": "https://www.manakonline.in",
        "statutory_source_ref": "BIS Act 2016, Section 13",
    },
    {
        "service_name": "Compulsory Registration (CRS) for Electronic and Solar Products",
        "service_type": "PRODUCT_CERTIFICATION",
        "description": "Simplified self-declaration registration process for electronics and solar equipment under MeitY / MNRE CRO schedules.",
        "eligibility_criteria": "Original Equipment Manufacturers (Domestic or Foreign) with authorized Indian representative (AIR).",
        "step_by_step_procedure": "Step 1: Submit product sample to a BIS recognized testing laboratory.\nStep 2: Obtain valid test report within 90 days.\nStep 3: Submit online CRS application with Test Report and Affidavit.\nStep 4: Scrutiny by BIS Officers.\nStep 5: Registration granted with R-Number.",
        "required_documents": ["Test Report from BIS-recognized lab", "Authorization of Indian Representative (AIR) for foreign OEMs", "Trademark registration certificate", "Affidavit undertaking of conformity"],
        "portal_url": "https://www.crsbis.in",
        "statutory_source_ref": "Electronics and Information Technology Goods (Requirement for Compulsory Registration) Order",
    },
    {
        "service_name": "Jeweller Registration for Hallmarking",
        "service_type": "HALLMARKING",
        "description": "Mandatory online registration for jewelers selling hallmarked gold and silver articles to consumers.",
        "eligibility_criteria": "Any retail or wholesale jeweler having valid GSTIN and business premises.",
        "step_by_step_procedure": "Step 1: Apply online through Manakonline portal.\nStep 2: Automatic issuance of registration certificate upon successful fee submission.\nStep 3: Deliver jewelry to recognized AHC for laser hallmarking.",
        "required_documents": ["GSTIN Registration Certificate", "Proof of business address", "Identity proof of proprietor/partner/director"],
        "portal_url": "https://www.manakonline.in/MANAK/hallmarkingJewellerRegistration",
        "statutory_source_ref": "BIS Hallmarking Regulations 2018",
    },
    {
        "service_name": "Consumer Grievance Redressal & BIS CARE Verification",
        "service_type": "CONSUMER_AFFAIRS",
        "description": "Public consumer service to verify genuine ISI marks, check jeweler HUID authenticity, and register formal complaints regarding substandard products.",
        "eligibility_criteria": "Open to all Indian consumers and commercial buyers.",
        "step_by_step_procedure": "Step 1: Download official BIS CARE Mobile App or visit BIS portal.\nStep 2: Enter 6-digit alphanumeric HUID or License/Registration R-number.\nStep 3: View verified manufacturer/jeweler details and registration validity.\nStep 4: Lodge complaint with photo evidence if product or mark is counterfeit.",
        "required_documents": ["Proof of purchase/invoice", "Photograph of product and standard mark", "Batch number"],
        "portal_url": "https://www.bis.gov.in/consumer-affairs/",
        "statutory_source_ref": "Consumer Protection Act 2019 & BIS Act 2016",
    },
]

SEED_LABORATORIES: List[Dict[str, Any]] = [
    {
        "lab_name": "BIS Central Laboratory (CL) Sahibabad",
        "registration_number": "BIS-LAB-CL-001",
        "lab_type": "CENTRAL_LAB",
        "location_city": "Ghaziabad",
        "location_state": "Uttar Pradesh",
        "address": "Plot No. 20/9, Site IV, Sahibabad Industrial Area, Ghaziabad, UP 201010",
        "accredited_standards": ["IS 16221 (Part 2)", "IS 13252 (Part 1)", "IS 302-1", "IS 1293", "IS 16046 (Part 2)"],
        "testing_capabilities": ["Photovoltaic Inverter Safety & Efficiency", "Dielectric & Insulation Testing", "IT Equipment Safety", "Battery Safety & Thermal Runaway", "IP Rating Dust & Water Ingress"],
        "contact_email": "cl@bis.gov.in",
        "contact_phone": "+91-120-2776031",
    },
    {
        "lab_name": "BIS Western Regional Laboratory (WRL) Mumbai",
        "registration_number": "BIS-LAB-WRL-002",
        "lab_type": "REGIONAL_LAB",
        "location_city": "Mumbai",
        "location_state": "Maharashtra",
        "address": "Manakalaya, E9, MIDC, Andheri (East), Mumbai, Maharashtra 400093",
        "accredited_standards": ["IS 16221 (Part 2)", "IS 13252 (Part 1)", "IS 302-1", "IS 1293"],
        "testing_capabilities": ["Grid-tied Inverter Testing", "Power Electronics Safety", "Plugs & Socket Outlets", "Creepage and Clearance Verification"],
        "contact_email": "wrl@bis.gov.in",
        "contact_phone": "+91-22-28329295",
    },
    {
        "lab_name": "BIS Southern Regional Laboratory (SRL) Chennai",
        "registration_number": "BIS-LAB-SRL-003",
        "lab_type": "REGIONAL_LAB",
        "location_city": "Chennai",
        "location_state": "Tamil Nadu",
        "address": "CIT Campus, 4th Cross Road, Taramani, Chennai, Tamil Nadu 600113",
        "accredited_standards": ["IS 16221 (Part 2)", "IS 13252 (Part 1)", "IS 16046 (Part 2)"],
        "testing_capabilities": ["Solar Inverter Islanding Protection", "Lithium Battery Cell & Pack Safety", "Environmental Endurance Testing"],
        "contact_email": "srl@bis.gov.in",
        "contact_phone": "+91-44-22541442",
    },
    {
        "lab_name": "BIS Northern Regional Laboratory (NRL) Mohali",
        "registration_number": "BIS-LAB-NRL-004",
        "lab_type": "REGIONAL_LAB",
        "location_city": "Mohali",
        "location_state": "Punjab",
        "address": "Plot No. 4-A, Sector 27-B, Madhya Marg, Chandigarh / Mohali 160019",
        "accredited_standards": ["IS 13252 (Part 1)", "IS 302-1", "IS 1293"],
        "testing_capabilities": ["Household Electrical Safety", "Insulation Resistance & Leakage Current", "Mechanical Impact & Enclosure Testing"],
        "contact_email": "nrl@bis.gov.in",
        "contact_phone": "+91-172-2650206",
    },
    {
        "lab_name": "BIS Eastern Regional Laboratory (ERL) Kolkata",
        "registration_number": "BIS-LAB-ERL-005",
        "lab_type": "REGIONAL_LAB",
        "location_city": "Kolkata",
        "location_state": "West Bengal",
        "address": "1/14, C.I.T. Scheme VII-M, V.I.P. Road, Kankurgachi, Kolkata, West Bengal 700054",
        "accredited_standards": ["IS 13252 (Part 1)", "IS 302-1", "IS 1293"],
        "testing_capabilities": ["Electrical Appliances Safety", "Material Flammability & Glow Wire Testing", "Plugs & Connectors"],
        "contact_email": "erl@bis.gov.in",
        "contact_phone": "+91-33-23207084",
    },
]

SEED_HALLMARKING: Dict[str, Any] = {
    "metal_type": "GOLD",
    "standard_number": "IS 1417: 2016",
    "purity_grades_json": [
        {"karat": "24K", "fineness": "999", "description": "Pure Gold / Bullion (99.9% pure)"},
        {"karat": "22K", "fineness": "916", "description": "22 Karat Gold (91.6% pure) - Most popular jewelry standard"},
        {"karat": "20K", "fineness": "833", "description": "20 Karat Gold (83.3% pure)"},
        {"karat": "18K", "fineness": "750", "description": "18 Karat Gold (75.0% pure) - Diamond & studded jewelry"},
        {"karat": "14K", "fineness": "585", "description": "14 Karat Gold (58.5% pure) - Modern lightweight jewelry"},
        {"karat": "9K", "fineness": "375", "description": "9 Karat Gold (37.5% pure)"},
    ],
    "mandatory_marks_json": [
        {"mark_name": "BIS Standard Mark", "description": "The triangular official logo of the Bureau of Indian Standards"},
        {"mark_name": "Purity & Fineness", "description": "Karat and fineness grade (e.g. 22K916 or 18K750)"},
        {"mark_name": "6-digit alphanumeric HUID", "description": "Unique laser-etched Hallmark Unique Identification code assigned to every individual piece"},
    ],
    "huid_structure_description": "The HUID is a 6-digit alphanumeric code (e.g., 'AB1234') laser-engraved onto every piece of jewelry at the Assaying and Hallmarking Centre (AHC). It creates an immutable digital trail ensuring traceability from jeweller to consumer.",
    "consumer_verification_steps": "1. Open the official BIS CARE Mobile application on iOS or Android.\n2. Tap 'Verify HUID'.\n3. Type the 6-character code etched on the piece of jewelry.\n4. App returns: Jeweller's registration number, AHC registration number, date of hallmarking, and certified purity grade.",
    "statutory_order_ref": "Hallmarking of Gold and Silver Artefacts Order, 2021 (Ministry of Consumer Affairs)",
}

SEED_STANDARDS: List[Dict[str, Any]] = [
    {
        "standard_number": "IS 16221 (Part 2)",
        "title": "Safety of Power Converters for Use in Photovoltaic Power Systems - Part 2: Particular Requirements for Inverters",
        "scope_summary": "Applies to grid-connected and standalone power converters/inverters intended for use in photovoltaic (PV) systems up to 1000 V AC. Mandatory under MeitY CRO Phase IV and MNRE Quality Control Orders.",
        "product_category": "SOLAR_INVERTERS",
        "is_mandatory": True,
        "cro_order_reference": "MeitY CRO Phase IV / MNRE Order 2017",
        "equivalent_international_standard": "IEC 62109-2: 2011",
        "revision_year": "2015",
        "clauses": [
            {
                "clause_number": "4.2.1",
                "clause_title": "Environmental Enclosure and Ingress Protection",
                "clause_text": "Inverters intended for outdoor installation shall provide an ingress protection rating of at least IP54 in accordance with IS/IEC 60529. Indoor inverters shall have at least IP20 protection.",
                "section_name": "Environmental & Construction",
                "page_number": 14,
                "parameter_key": "enclosure_ip_rating",
                "expected_unit": "rating",
                "comparison_operator": ">=",
                "threshold_min": "IP54",
                "expected_value": "IP54",
            },
            {
                "clause_number": "5.1.4",
                "clause_title": "Clearance and Creepage Distances",
                "clause_text": "For working voltages up to 600 V RMS across reinforced insulation, the creepage distance across printed wiring boards and insulation barriers shall not be less than 6.3 mm.",
                "section_name": "Insulation and Spacings",
                "page_number": 19,
                "parameter_key": "creepage_distance_mm",
                "expected_unit": "mm",
                "comparison_operator": ">=",
                "threshold_min": "6.3",
                "expected_value": "6.3 mm",
            },
            {
                "clause_number": "5.2.3",
                "clause_title": "Dielectric Strength Voltage Test",
                "clause_text": "The power converter shall withstand a dielectric test voltage of 2500 V RMS (or 3535 V DC) applied between primary input circuits and accessible conductive enclosure for a continuous duration of 60 seconds without flashover or breakdown.",
                "section_name": "Electrical Safety",
                "page_number": 22,
                "parameter_key": "dielectric_test_voltage_v",
                "expected_unit": "V",
                "comparison_operator": ">=",
                "threshold_min": "2500",
                "expected_value": "2500 V RMS",
            },
            {
                "clause_number": "5.3",
                "clause_title": "Anti-Islanding Protection and Disconnection",
                "clause_text": "Grid-connected inverters shall incorporate an automatic anti-islanding protection mechanism. Upon disconnection or de-energization of the utility AC grid, the inverter shall disconnect and cease energizing the grid within a maximum trip time of 2.0 seconds.",
                "section_name": "Grid Interconnection Safety",
                "page_number": 27,
                "parameter_key": "anti_islanding_trip_time_s",
                "expected_unit": "s",
                "comparison_operator": "<=",
                "threshold_max": "2.0",
                "expected_value": "2.0 s",
            },
            {
                "clause_number": "6.4",
                "clause_title": "Maximum Accessible Surface Temperature",
                "clause_text": "Under maximum rated operating power at an ambient temperature of 40 deg C, accessible external metal surface temperatures shall not exceed 70.0 deg C.",
                "section_name": "Thermal Safety",
                "page_number": 31,
                "parameter_key": "max_touch_temperature_degc",
                "expected_unit": "degC",
                "comparison_operator": "<=",
                "threshold_max": "70.0",
                "expected_value": "70.0 degC",
            },
            {
                "clause_number": "7.2",
                "clause_title": "Protective Earthing Resistance",
                "clause_text": "The resistance between the protective grounding terminal and any accessible dead metal part intended to be earthed shall not exceed 0.1 Ohm under a test current of 25 A.",
                "section_name": "Earthing Integrity",
                "page_number": 36,
                "parameter_key": "earthing_resistance_ohm",
                "expected_unit": "Ohm",
                "comparison_operator": "<=",
                "threshold_max": "0.1",
                "expected_value": "0.1 Ohm",
            },
        ],
        "testing_requirements": [
            {
                "test_name": "Anti-Islanding Disconnection Test",
                "test_method": "Apply RLC resonant load balanced to inverter output; open grid circuit breaker; record disconnection waveform on digital storage oscilloscope.",
                "required_apparatus": "Programmable AC grid simulator, RLC resonant load bank, 4-channel DSO with voltage/current probes.",
                "sampling_criteria": "1 representative unit of each power rating family.",
                "source_reference": "IS 16221 (Part 2): 2015, Clause 5.3",
            },
            {
                "test_name": "Dielectric Withstand Test",
                "test_method": "Apply 2500 V RMS sinusoidal 50 Hz voltage between shorted PV+/PV- terminals and ground chassis for 60 s.",
                "required_apparatus": "Calibrated Hipot Tester with trip current threshold set to 5 mA.",
                "sampling_criteria": "100% production routine test or type test on 1 prototype.",
                "source_reference": "IS 16221 (Part 2): 2015, Clause 5.2.3",
            },
        ],
    },
    {
        "standard_number": "IS 13252 (Part 1)",
        "title": "Information Technology Equipment - Safety - General Requirements",
        "scope_summary": "Applicable to mains-powered or battery-powered information technology equipment including power adapters, desktop computers, data storage units, and telecommunication terminal equipment. Mandatory under MeitY CRO Phase I.",
        "product_category": "IT_ELECTRONICS",
        "is_mandatory": True,
        "cro_order_reference": "MeitY CRO Phase I Order 2012",
        "equivalent_international_standard": "IEC 60950-1: 2005",
        "revision_year": "2010",
        "clauses": [
            {
                "clause_number": "1.5.1",
                "clause_title": "Polymeric Materials Flammability Rating",
                "clause_text": "Polymeric materials used for fire enclosures shall have a flammability classification of V-0 or V-1 when evaluated according to IS 11731 (Part 2) or UL 94.",
                "section_name": "General Safety",
                "page_number": 12,
                "parameter_key": "flammability_class",
                "expected_unit": "grade",
                "comparison_operator": "==",
                "expected_value": "V-0",
            },
            {
                "clause_number": "2.1.1",
                "clause_title": "Protection from Electric Shock (SELV Voltage Limits)",
                "clause_text": "Under normal operating conditions, accessible voltage in Safety Extra-Low Voltage (SELV) circuits shall not exceed 42.4 V peak or 60 V DC.",
                "section_name": "Shock Protection",
                "page_number": 18,
                "parameter_key": "selv_max_voltage_v",
                "expected_unit": "V",
                "comparison_operator": "<=",
                "threshold_max": "60.0",
                "expected_value": "60.0 V DC",
            },
            {
                "clause_number": "2.9.2",
                "clause_title": "Humidity Conditioning and Insulation Resistance",
                "clause_text": "Following humidity conditioning at 91% to 95% relative humidity for 48 hours, the insulation resistance shall not be less than 2.0 MOhm.",
                "section_name": "Insulation",
                "page_number": 26,
                "parameter_key": "insulation_resistance_mohm",
                "expected_unit": "MOhm",
                "comparison_operator": ">=",
                "threshold_min": "2.0",
                "expected_value": "2.0 MOhm",
            },
            {
                "clause_number": "5.2.2",
                "clause_title": "Electric Strength Test",
                "clause_text": "Insulation between primary circuits and secondary SELV circuits shall withstand an AC test voltage of 3000 V RMS (or 4242 V DC) for 60 seconds.",
                "section_name": "Electric Strength",
                "page_number": 45,
                "parameter_key": "hipot_voltage_primary_secondary_v",
                "expected_unit": "V",
                "comparison_operator": ">=",
                "threshold_min": "3000",
                "expected_value": "3000 V RMS",
            },
        ],
        "testing_requirements": [
            {
                "test_name": "SELV Voltage Verification Under Single Fault",
                "test_method": "Simulate single component failures; monitor secondary output with peak-reading voltmeter.",
                "required_apparatus": "Digital oscilloscope, high-voltage differential probes.",
                "sampling_criteria": "Type test on 1 prototype.",
                "source_reference": "IS 13252 (Part 1): 2010, Clause 2.1.1",
            },
        ],
    },
    {
        "standard_number": "IS 302-1",
        "title": "Safety of Household and Similar Electrical Appliances - Part 1: General Requirements",
        "scope_summary": "Safety of electrical appliances for household and similar purposes with rated voltage not more than 250 V for single-phase appliances. Mandatory under Quality Control Orders.",
        "product_category": "HOUSEHOLD_APPLIANCES",
        "is_mandatory": True,
        "cro_order_reference": "DPIIT Electrical Appliances QCO",
        "equivalent_international_standard": "IEC 60335-1: 2006",
        "revision_year": "2008",
        "clauses": [
            {
                "clause_number": "8.1",
                "clause_title": "Protection Against Access to Live Parts",
                "clause_text": "Appliances shall be constructed so that there is adequate protection against accidental contact with live parts when tested with standard test probe B (IS 1401).",
                "section_name": "Physical Protection",
                "page_number": 15,
                "parameter_key": "probe_accessibility",
                "expected_unit": "boolean",
                "comparison_operator": "==",
                "expected_value": "NON_ACCESSIBLE",
            },
            {
                "clause_number": "13.2",
                "clause_title": "Leakage Current and Electric Strength at Operating Temperature",
                "clause_text": "The leakage current of Class I portable appliances at operating temperature shall not exceed 0.75 mA under rated supply voltage.",
                "section_name": "Electrical Safety",
                "page_number": 23,
                "parameter_key": "leakage_current_ma",
                "expected_unit": "mA",
                "comparison_operator": "<=",
                "threshold_max": "0.75",
                "expected_value": "0.75 mA",
            },
        ],
        "testing_requirements": [
            {
                "test_name": "Operating Temperature Leakage Current Test",
                "test_method": "Operate appliance at 1.15 times rated power input until steady state; measure current with IEC 60990 measuring network.",
                "required_apparatus": "Variable autotransformer, true-RMS leakage current meter.",
                "sampling_criteria": "Type test sample of 3 units.",
                "source_reference": "IS 302-1: 2008, Clause 13.2",
            },
        ],
    },
    {
        "standard_number": "IS 1293",
        "title": "Plugs and Socket-Outlets for Household and Similar Purposes of Rated Voltage up to and Including 250 V and Rated Current up to and Including 16 A",
        "scope_summary": "Specifies safety and dimensional requirements for 6 A and 16 A plugs and socket-outlets in India. Mandatory QCO.",
        "product_category": "ELECTRICAL_ACCESSORIES",
        "is_mandatory": True,
        "cro_order_reference": "DPIIT Plugs and Sockets QCO 2020",
        "equivalent_international_standard": "BS 546 (adapted)",
        "revision_year": "2019",
        "clauses": [
            {
                "clause_number": "9.1",
                "clause_title": "Dimensional Verification of Plugs",
                "clause_text": "For 6 A 3-pin plugs, the live and neutral pins shall have a nominal diameter of 5.08 mm (tolerances 5.03 mm to 5.13 mm) and a pin length of 19.05 mm (+- 0.5 mm).",
                "section_name": "Dimensions",
                "page_number": 11,
                "parameter_key": "pin_diameter_6a_mm",
                "expected_unit": "mm",
                "comparison_operator": "RANGE",
                "threshold_min": "5.03",
                "threshold_max": "5.13",
                "expected_value": "5.08 mm",
            },
            {
                "clause_number": "10.1",
                "clause_title": "Protection Against Electric Shock",
                "clause_text": "Socket-outlets shall be constructed so that live parts are not accessible when the plug is in partial engagement.",
                "section_name": "Shock Protection",
                "page_number": 16,
                "parameter_key": "shutter_safety",
                "expected_unit": "boolean",
                "comparison_operator": "==",
                "expected_value": "COMPLIANT",
            },
        ],
        "testing_requirements": [
            {
                "test_name": "Dimensional Go/No-Go Gauge Test",
                "test_method": "Verify plug pin diameter, spacing, and length using certified IS 1293 steel gauges.",
                "required_apparatus": "Standard IS 1293 Go and No-Go gauges, vernier micrometer.",
                "sampling_criteria": "10 samples from batch.",
                "source_reference": "IS 1293: 2019, Clause 9.1",
            },
        ],
    },
    {
        "standard_number": "IS 16046 (Part 2)",
        "title": "Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes - Secondary Lithium Cells and Batteries for Use in Portable Applications",
        "scope_summary": "Safety requirements for portable secondary lithium cells and batteries used in electronic equipment, power banks, and portable energy storage.",
        "product_category": "BATTERIES",
        "is_mandatory": True,
        "cro_order_reference": "MeitY CRO Phase II Order",
        "equivalent_international_standard": "IEC 62133-2: 2017",
        "revision_year": "2018",
        "clauses": [
            {
                "clause_number": "7.2.1",
                "clause_title": "Continuous Charging at Constant Voltage",
                "clause_text": "A fully charged cell shall remain connected to a constant voltage charger for 7 days at ambient temperature without fire, explosion, or leakage.",
                "section_name": "Charging Safety",
                "page_number": 14,
                "parameter_key": "continuous_charge_safety",
                "expected_unit": "status",
                "comparison_operator": "==",
                "expected_value": "NO_FIRE_NO_EXPLOSION",
            },
            {
                "clause_number": "7.3.2",
                "clause_title": "External Short Circuit Test",
                "clause_text": "A fully charged battery shall be short-circuited by connecting the positive and negative terminals with a resistance not exceeding 80 mOhm at 55 deg C. The battery shall not catch fire or explode.",
                "section_name": "Short Circuit",
                "page_number": 18,
                "parameter_key": "short_circuit_flame_test",
                "expected_unit": "status",
                "comparison_operator": "==",
                "expected_value": "NO_FIRE_NO_EXPLOSION",
            },
        ],
        "testing_requirements": [
            {
                "test_name": "Battery External Short Circuit Test",
                "test_method": "Subject battery to short circuit through 80 mOhm resistor inside thermal chamber at 55 deg C until temperature decays.",
                "required_apparatus": "Thermal test chamber, precision 80 mOhm shunt, thermocouple datalogger.",
                "sampling_criteria": "5 fully charged battery packs.",
                "source_reference": "IS 16046 (Part 2): 2018, Clause 7.3.2",
            },
        ],
    },
    {
        "standard_number": "IS 17526:2021",
        "title": "Vacuum Insulated Stainless Steel Flasks, Bottles and Containers - Specification",
        "scope_summary": "Specifies requirements and test methods for double-walled vacuum insulated stainless steel flasks, bottles, and domestic containers up to 2000 ml. Mandatory under DPIIT Quality Control Order (QCO) requiring Scheme I (ISI Mark) certification.",
        "product_category": "DOMESTIC_CONTAINERS",
        "is_mandatory": True,
        "cro_order_reference": "DPIIT Quality Control Order 2023 / Gazette S.O. 1234(E)",
        "equivalent_international_standard": "EN 12546-1 (adapted)",
        "revision_year": "2021",
        "clauses": [
            {
                "clause_number": "4.1",
                "clause_title": "Material Grade and Food-Contact Conformity",
                "clause_text": "All fluid-contact metallic surfaces shall be manufactured from certified Austenitic Stainless Steel Grade SS 304 (04Cr18Ni10 per IS 6911) or SS 316. Polymer caps and gaskets shall comply with IS 9845 for food-grade safety.",
                "section_name": "Material Specification",
                "page_number": 4,
                "parameter_key": "material_grade_conformity",
                "expected_unit": "grade",
                "comparison_operator": "==",
                "expected_value": "SS 304 / SS 316",
            },
            {
                "clause_number": "5.1",
                "clause_title": "Fabrication, Capacity and Seal Integrity",
                "clause_text": "The container shall exhibit zero leakage, seal loss, distortion, or structural failure when subjected to hydrostatic pressure testing at 20 kPa for 60 seconds.",
                "section_name": "Physical & Hydraulic Integrity",
                "page_number": 7,
                "parameter_key": "seal_leakage_status",
                "expected_unit": "status",
                "comparison_operator": "==",
                "expected_value": "NO_LEAKAGE",
            },
            {
                "clause_number": "5.3",
                "clause_title": "Thermal Insulation Performance Test",
                "clause_text": "The flask shall be filled with boiling water (minimum 95 deg C) and maintained in an ambient temperature of 20 deg C +- 2 deg C for 6 hours. Final fluid retention temperature shall not be less than 65.0 deg C.",
                "section_name": "Thermal Insulation",
                "page_number": 10,
                "parameter_key": "thermal_retention_temp_degc",
                "expected_unit": "degC",
                "comparison_operator": ">=",
                "threshold_min": "65.0",
                "expected_value": "65.0 degC",
            },
            {
                "clause_number": "5.6",
                "clause_title": "Drop Impact and Handle Mechanical Shock Resistance",
                "clause_text": "The flask shall be filled to nominal capacity and dropped from a height of 1.0 m onto a hardwood floor 3 times without cracking, loss of vacuum insulation, or fluid leakage.",
                "section_name": "Mechanical Durability",
                "page_number": 12,
                "parameter_key": "drop_impact_status",
                "expected_unit": "status",
                "comparison_operator": "==",
                "expected_value": "NO_LEAKAGE_NO_CRACK",
            },
            {
                "clause_number": "7.1",
                "clause_title": "Durable Marking, Labeling & ISI Standard Mark",
                "clause_text": "Each flask shall be permanently marked with manufacturer name/trademark, nominal capacity (ml), standard number IS 17526, and the BIS Standard Mark (ISI logo) with license number CM/L-XXXXXXXXX.",
                "section_name": "Marking & Scheme I Compliance",
                "page_number": 16,
                "parameter_key": "isi_mark_compliance",
                "expected_unit": "status",
                "comparison_operator": "==",
                "expected_value": "COMPLIANT_ISI_MARKING",
            },
        ],
        "testing_requirements": [
            {
                "test_name": "Thermal Performance 6-Hour Retention Test",
                "test_method": "Fill flask with boiling water at >= 95 deg C; seal lid; incubate at 20 deg C ambient for 6 hours; measure core fluid temperature with calibrated digital probe.",
                "required_apparatus": "Digital precision RTD probe, environmental temperature chamber.",
                "sampling_criteria": "3 flasks from production lot.",
                "source_reference": "IS 17526: 2021, Clause 5.3",
            },
            {
                "test_name": "Material Chemical Composition Spectrometry",
                "test_method": "Optical emission spectrometry / XRF verification of Chromium (18-20%) and Nickel (8-10.5%) for SS 304.",
                "required_apparatus": "OES Spectrometer / Handheld XRF Alloy Analyzer.",
                "sampling_criteria": "1 test coupon per material heat batch.",
                "source_reference": "IS 17526: 2021, Clause 4.1 & IS 6911",
            },
        ],
    },
]

SEED_RELATED_STANDARDS: List[Dict[str, Any]] = [
    {
        "primary_standard": "IS 16221 (Part 2)",
        "related_standard": "IS 16221 (Part 1)",
        "relationship_type": "PARENT_SERIES",
        "notes": "Part 1 contains general safety requirements for all power converters in PV systems; Part 2 specifies particular requirements for inverters.",
    },
    {
        "primary_standard": "IS 16221 (Part 2)",
        "related_standard": "IS/IEC 61727",
        "relationship_type": "NORMATIVE_REFERENCE",
        "notes": "Photovoltaic (PV) systems - Characteristics of the utility interface.",
    },
    {
        "primary_standard": "IS 16221 (Part 2)",
        "related_standard": "IS/IEC 62116",
        "relationship_type": "TESTING_METHOD",
        "notes": "Utility-interconnected photovoltaic inverters - Test procedure of islanding prevention measures.",
    },
    {
        "primary_standard": "IS 13252 (Part 1)",
        "related_standard": "IS 1293",
        "relationship_type": "SUBSIDIARY",
        "notes": "Plugs attached to IT equipment cords must comply with IS 1293 dimensions.",
    },
    {
        "primary_standard": "IS 16221 (Part 2)",
        "related_standard": "IS 16046 (Part 2)",
        "relationship_type": "NORMATIVE_REFERENCE",
        "notes": "Applies when hybrid solar inverters incorporate internal lithium-ion battery storage systems.",
    },
]
